# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pN7uLV0fe4OOBET8o4s-g6SsSCmj2uVg
"""

nome = input ("Olá, sou sua calculadora em python. Como você se chama?")
print ("Olá", nome,"!", "Quer calcular algo?")
resposta = input ("Digite sim ou não")
while resposta == "sim":
  valor_1 = input ("Digite o primeiro valor")
  valor_2 = input ("Digite o segundo valor")
  valor_1 = float (valor_1)
  valor_2 = float (valor_2)
  Operação = input ("Escolha uma das operações básicas: Adição, Subtração, Multiplicação ou Divisão")
  if Operação == "Adição" or Operação == "adição" or Operação == "adiçao" or Operação == "adicao" or Operação == "Adiçao" or Operação == "Adicão" or Operação == "Adicao":
    Adição = float (valor_1 + valor_2)
    print ("O resultado da adição é:", Adição)
  if Operação == "Subtração" or Operação == "Subtraçao" or Operação == "Subtracão" or Operação == "Subtracao" or Operação == "subtração" or Operação == "subtraçao" or Operação == "subtracão" or Operação == "subtracao":
    Subtração = float (valor_1 - valor_2)
    print ("O resultado da subtração é:", Subtração)
  if Operação == "Multiplicação" or Operação == "Multiplicaçao" or Operação == "Multiplicacão" or Operação == "Multiplicacao" or Operação == "multiplicação" or Operação == "multiplicaçao" or Operação == "multiplicacao":
    Multiplicação = float (valor_1 * valor_2)
    print ("O resultado da multiplicação é", Multiplicação)
  if Operação == "Divisão" or Operação == "Divisao" or Operação == "divisão" or Operação == "divisao":
    Divisão = float (valor_1 / valor_2)
    print ("O resultado da divisão é:", Divisão)
  print (nome, "Quer calcular mais alguma coisa?")
  resposta = input ("Digite sim ou não")
if resposta == "não":
  print ("Até a próxima, pessoal!")